red_list = [
    "kill myself", "kms", "end my life", "take my own life", "want to die",
    "don't want to live anymore", "want to disappear forever", "ready to end it all",
    "suicide", "suicidal", "commit suicide", "committing suicide", "final exit",
    "overdose", "pills and alcohol", "hanging myself", "jumping off a bridge",
    "slitting my wrists", "got a gun", "how to tie a noose",
    "no reason to live", "goodbye cruel world", "can't go on",
    "it's over for me", "there's no other way out",
    "maybe the world would be better without me",
    "i’ve written goodbye letters",
    "i’m planning to end it all tonight",
    "i’m tired of being alive",
    "i just want it to stop forever",
    "i’ve made peace with not waking up",
    "how do i die painlessly",
    "i already said goodbye to my friends",
    "i want to jump and never come back",
    "how many pills does it take to die",
    "there’s nothing left for me here",
    "this is my last message",
    "i just want it to be over",
    "i’m ready to vanish forever",
    "please don’t try to stop me this time",
    "how to die peacefully at home",
    "i'm looking for ways to not wake up",
    "it's my final night",
]


yellow_list = [
    "hopeless", "worthless", "crippling depression", "can't get out of bed",
    "numb inside", "everything is pointless", "unbearable pain", "crushing weight",
    "drowning", "panic attack", "can't breathe", "hyperventilating",
    "feel like I'm dying", "losing my mind", "spiraling out of control",
    "overwhelmed", "self-harm", "cutting myself", "want to hurt myself",
    "hitting myself", "burning myself", "I'm not safe", "scared for my life",
    "he hits me", "she abuses me", "being threatened", "in danger",
    "i feel invisible", "i’m drowning and no one sees it",
    "i cry myself to sleep", "i can’t eat or sleep anymore",
    "i'm exhausted from pretending i'm okay",
    "everything feels so heavy", "my brain won't stop screaming",
    "i feel like a burden", "i just want to sleep forever",
    "no one would notice if i vanished", "i'm scared of myself",
    "i keep messing everything up", "i'm not strong enough for this",
    "it's always dark inside my head", "i hate being alive",
    "i just want a break from existing", "i'm emotionally numb",
    "no one understands how broken i feel", "i keep hurting inside",
]
