name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.EC2_KEY }}

    - name: Add host to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} <<'SSH'
          set -e

          # Create deployment directory
          sudo mkdir -p /opt/sarthi
          sudo chown -R $USER:$USER /opt/sarthi

          # Stop service if running
          sudo systemctl stop sarthi || true

          # Backup old deployment
          cd /opt/sarthi
          if [ -d "current" ]; then
            mv current backup_$(date +%Y%m%d_%H%M%S)
          fi

          # Clone repo
          git clone https://github.com/${{ github.repository }}.git current
          cd current

          # Setup Python environment
          python3.12 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

          # Create .env file line-by-line
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env
          echo "JWT_ALGORITHM=HS256" >> .env
          echo "JWT_EXPIRATION_HOURS=1" >> .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "PINECONE_API_KEY=${{ secrets.PINECONE_API_KEY }}" >> .env
          echo "PINECONE_INDEX=${{ secrets.PINECONE_INDEX }}" >> .env
          echo "PINECONE_NAMESPACE=distress" >> .env
          echo "OPENAI_EMBED_MODEL=text-embedding-3-large" >> .env
          echo "ZEPTOMAIL_TOKEN=${{ secrets.ZEPTOMAIL_TOKEN }}" >> .env
          echo "ZEPTOMAIL_FROM_DOMAIN=noreply@${{ secrets.DOMAIN_NAME }}" >> .env
          echo "ZEPTOMAIL_FROM_NAME=Sarthi" >> .env
          echo "WHATSAPP_ACCESS_TOKEN=${{ secrets.WHATSAPP_ACCESS_TOKEN }}" >> .env
          echo "WHATSAPP_PHONE_NUMBER_ID=${{ secrets.WHATSAPP_PHONE_NUMBER_ID }}" >> .env
          echo "WHATSAPP_TEMPLATE_NAME=authentication" >> .env

          chmod 600 .env
          sudo chown -R ubuntu:ubuntu /opt/sarthi/current

          # Test if app loads
          source venv/bin/activate
          python -c "from app.main import app; print('✅ App loads successfully')"
SSH

    - name: Start Services
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
          sudo systemctl start sarthi
          sleep 5
          sudo systemctl status sarthi --no-pager
        '

    - name: Health Check
      run: |
        sleep 10
        curl -f http://${{ secrets.EC2_HOST }}/health || exit 1
        echo "✅ Deployment successful"
