# 4 — Deploy to EC2 instance
- name: Deploy to EC2
  run: |
    ssh -A "${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}" <<EOF
      set -euo pipefail

      REPO="manasjh1/sarthiv7"

      # ── Prepare /opt/sarthi
      sudo mkdir -p /opt/sarthi
      # CORRECTED LINE: Use the explicit EC2_USER secret instead of the ambiguous $USER variable
      sudo chown -R "${{ secrets.EC2_USER }}":"${{ secrets.EC2_USER }}" /opt/sarthi
      cd /opt/sarthi

      # ── Stop running service if any
      sudo systemctl stop sarthi || true

      # ── Backup current release
      if [ -d current ]; then
        mv current "backup_$(date +%Y%m%d_%H%M%S)"
      fi

      # ── Clone repo with SSH (requires deploy key)
      git clone --depth 1 git@github.com:$REPO.git current
      cd current

      # ── Python venv and install requirements
      python3.12 -m venv venv
      source venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt

      # ── Create .env file with secrets
      cat > .env <<ENVEOF
      DATABASE_URL=${{ secrets.DATABASE_URL }}
      JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
      JWT_ALGORITHM=HS256
      JWT_EXPIRATION_HOURS=1
      OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
      PINECONE_API_KEY=${{ secrets.PINECONE_API_KEY }}
      PINECONE_INDEX=${{ secrets.PINECONE_INDEX }}
      PINECONE_NAMESPACE=distress
      OPENAI_EMBED_MODEL=text-embedding-3-large
      ZEPTOMAIL_TOKEN=${{ secrets.ZEPTOMAIL_TOKEN }}
      ZEPTOMAIL_FROM_DOMAIN=noreply@${{ secrets.DOMAIN_NAME }}
      ZEPTOMAIL_FROM_NAME=Sarthi
      WHATSAPP_ACCESS_TOKEN=${{ secrets.WHATSAPP_ACCESS_TOKEN }}
      WHATSAPP_PHONE_NUMBER_ID=${{ secrets.WHATSAPP_PHONE_NUMBER_ID }}
      WHATSAPP_TEMPLATE_NAME=authentication
      ENVEOF

      chmod 600 .env
      # This second chown is also fine, as it explicitly uses 'ubuntu'
      sudo chown -R ubuntu:ubuntu /opt/sarthi/current

      # ── Smoke test
      source venv/bin/activate
      python <<PY
      from app.main import app
      print("✅ App loaded successfully")
      PY
    EOF