- name: Deploy to EC2
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
          set -euo pipefail

          # Prepare /opt/sarthi directory
          sudo mkdir -p /opt/sarthi
          sudo chown -R ${{ secrets.EC2_USER }}:${{ secrets.EC2_USER }} /opt/sarthi
          cd /opt/sarthi

          # Stop running service if any
          sudo systemctl stop sarthi || true

          # Backup current release
          if [ -d current ]; then
            mv current backup_$(date +%Y%m%d_%H%M%S)
          fi

          # Clone fresh code (using HTTPS, not SSH)
          git clone --depth 1 https://github.com/${{ github.repository }}.git current
          cd current

          # Create Python virtual environment
          python3.12 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

          # Create .env file with secrets
          cat > .env << EOF
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
          JWT_ALGORITHM=HS256
          JWT_EXPIRATION_HOURS=1
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          PINECONE_API_KEY=${{ secrets.PINECONE_API_KEY }}
          PINECONE_INDEX=${{ secrets.PINECONE_INDEX }}
          PINECONE_NAMESPACE=distress
          OPENAI_EMBED_MODEL=text-embedding-3-large
          ZEPTOMAIL_TOKEN=${{ secrets.ZEPTOMAIL_TOKEN }}
          ZEPTOMAIL_FROM_DOMAIN=noreply@sarthi.me
          ZEPTOMAIL_FROM_NAME=Sarthi
          WHATSAPP_ACCESS_TOKEN=${{ secrets.WHATSAPP_ACCESS_TOKEN }}
          WHATSAPP_PHONE_NUMBER_ID=${{ secrets.WHATSAPP_PHONE_NUMBER_ID }}
          WHATSAPP_TEMPLATE_NAME=authentication
          EOF

          chmod 600 .env
          sudo chown -R ${{ secrets.EC2_USER }}:${{ secrets.EC2_USER }} /opt/sarthi/current

          # Test application loads successfully
          source venv/bin/activate
          python -c "from app.main import app; print(\"✅ App loaded successfully\")"
        '